more_stop_words = frozenset(['00', '000', '2018', 'ability', 'able', 'accept',
    'access', 'accommodation', 'action', 'activity', 'affirmative', 'age',
    'agencies', 'agency', 'algorithms', 'alias', 'analysis', 'analyze',
    'applicants', 'application', 'applications', 'apply', 'applying',
    'approaches', 'appropriate', 'approved', 'apps', 'architecture', 'area',
    'areas', 'asset', 'assets', 'authorization', 'available', 'background',
    'based', 'basic', 'basis', 'benefit', 'benefits', 'best', 'better', 'big',
    'billions', 'brand', 'bring', 'broad', 'build', 'building', 'business',
    'businesses', 'candidate', 'candidateaccommodations', 'candidates', 'care',
    'career', 'careers', 'cases', 'celebrate', 'challenges', 'challenging',
    'chance', 'change', 'citizenship', 'city', 'class', 'client', 'clients',
    'closely', 'cloud', 'code', 'coding', 'collaborate', 'collaboration',
    'color', 'com', 'committed', 'communication', 'community', 'companies',
    'company', 'complex', 'computer', 'computing', 'concepts', 'consider',
    'consistent', 'consulting', 'continue', 'contribute', 'control', 'core',
    'cover', 'create', 'creating', 'creative', 'critical', 'culture',
    'current', 'currently', 'customer', 'customers', 'cutting', 'data', 'day',
    'decisions', 'defect', 'degree', 'deliver', 'delivery', 'demonstrate',
    'demonstrated', 'description', 'design', 'designing', 'desired', 'develop',
    'developer', 'developers', 'developing', 'development', 'devices',
    'difference', 'different', 'directly', 'disability', 'display', 'diverse',
    'diversity', 'does', 'doing', 'drive', 'driven', 'edge', 'eeo',
    'effective', 'emailing', 'employee', 'employees', 'employer', 'employment',
    'end', 'engagement', 'engineer', 'engineering', 'engineers', 'ensure',
    'enterprise', 'environment', 'equal', 'equivalent', 'evaluate', 'events',
    'excellent', 'existing', 'experience', 'experiences', 'expertise',
    'explore', 'familiarity', 'fast', 'features', 'fees', 'field', 'focus',
    'focused', 'following', 'forward', 'functional', 'future', 'gender',
    'general', 'generation', 'getting', 'given', 'global', 'globe', 'goals',
    'good', 'grand', 'great', 'grow', 'growing', 'growth', 'hands',
    'help', 'helping', 'high', 'highly', 'hire', 'hiring', 'house', 'ideal',
    'identity', 'impact', 'implement', 'implementation', 'implementing',
    'improve', 'include', 'including', 'individual', 'individuals', 'industry',
    'information', 'infrastructure', 'innovation', 'innovative', 'insights',
    'intelligence', 'internal', 'issues', 'job', 'jobs', 'join', 'just', 'key',
    'know', 'knowledge', 'languages', 'large', 'largest', 'lead', 'leaders',
    'leadership', 'leading', 'learn', 'learning', 'let', 'level', 'leveraging',
    'libraries', 'life', 'like', 'limited', 'll', 'located', 'location',
    'locations', 'long', 'looking', 'love', 'machine', 'make', 'making',
    'manage', 'management', 'marin', 'marital', 'massive', 'media', 'meet',
    'member', 'members', 'methodologies', 'methods', 'millions', 'minimum', 'mission',
    'modern', 'motivated', 'national', 'need', 'needed', 'needs', 'new', 'ny',
    'office', 'offices', 'open', 'operations', 'opportunities', 'opportunity',
    'optimize', 'oral', 'organization', 'orientation', 'oriented', 'origin',
    'paced', 'participate', 'partner', 'partners', 'passion', 'passionate',
    'people', 'performance', 'planning', 'platform', 'plus', 'policy',
    'position', 'possible', 'potential', 'practical', 'practices', 'preferred',
    'present', 'private', 'problem', 'problems', 'process', 'processes',
    'product', 'production', 'products', 'professional',
    'program', 'programming', 'programs', 'project', 'projects', 'proud',
    'provide', 'provides', 'qualifications', 'qualified', 'quality',
    'questions', 'quickly', 'race', 'range', 'rapidly', 'real', 'record',
    'recruiting', 'recruitment', 'regardless', 'related', 'relevant',
    'religion', 'required', 'requirements', 'requires', 'resolutions',
    'resources', 'responsibilities', 'responsible', 'results', 'resume',
    'resumes', 'right', 'role', 'rounds', 'salary', 'san', 'scale', 'science',
    'sciences', 'search', 'seeking', 'self', 'self', 'service', 'services',
    'set', 'sex', 'sexual', 'site', 'skills', 'small', 'social', 'software',
    'solution', 'solutions', 'solve', 'solving', 'source', 'special',
    'standard', 'standards', 'start', 'state', 'states', 'status', 'stay', 'strategic',
    'strong', 'structures', 'succeed', 'success', 'successful', 'support',
    'systems', 'talented', 'team', 'teams', 'technical', 'techniques',
    'technologies', 'technology', 'test', 'testing', 'think', 'thrive',
    'tools', 'total', 'track', 'type', 'understand', 'understanding', 'united',
    'unsolicited', 'usa', 'use', 'used', 'user', 'users', 'using', 'value',
    'variety', 'various', 'verbal', 'verily', 'veteran', 'view', 'visual',
    'want', 'ways', 'web', 'wide', 'work', 'working', 'workplace', 'world',
    'written', 'www', 'year', 'years', 'content','stakeholders', 'competitive', 'expert',
    'left', 'novel','meaningful', 'metrics', 'non', 'writing','identify', 'collaborative',
    'come', 'discovery', 'independently','assist','enable', 'exciting', 'fit', 'https', 'line',
    'attention', 'creation', 'discover', 'duties', 'emerging', 'effectively','reporting',
    'size', 'bold','comfortable', 'online', 'perform',  'define', 'efficient', 'environments',
    '100', 'capabilities', 'providing', 'specific', 'receive', 'solid',  'excel', 'family', 'goal',
    'evaluation', 'execute', 'maintain', 'similar', 'offer', 'regard', 'achieve', 'proficiency', 'way',
    'multiple', 'digital', 'communicate', 'tech', 'align', 'decision', 'leverage', 'major',
    'approach', 'expression', 'protected', 'initiatives', 'public','tasks', 'staff', 'style',
    'pipelines', 'significant',  'managing','place','10', 'desire', 'paid', 'compensation',
    'consideration','latest', 'research', 'models', 'criminal', 'google', 'medical', 'amazon',
    'spotify', 'akuna', 'gartner', 'microsoft', 'vision', 'dental', 'supportive', 'residence'
])
# removed word medical because it shows up too often in benefits section
# Removing company names because they show up too much