more_stop_words = frozenset([
    'software', 'experience', 'google', 'development', 'team', 'data', 'design',
    'work', 'new', 'status', 'programming', 'engineers', 'opportunity', 'technologies',
    'skills', 'disability', 'computer', 'systems', 'technical', 'job',
    'resumes', 'application', 'engineering', 'equal', 'applications', 'time', 
    'requirements', 'ensure', 'building', 'information', 'need', 'customers', 'code', 
    'tools', 'science', 'related', 'employees', 'required', 'location', 'usa', 'platform', 
    'years', 'marin', 'business', 'com', 'gender', 'orientation', 'build', 'life', 
    'products', 'product', 'solutions', 'preferred', 'based', 'best', 'employer', 
    'national', 'role', 'working', 'support', 'problems', 'qualifications', 'verily', 
    'accept', 'regardless', 'eeo', 'looking', 'site', 'san', 'including', 'company', 
    'world', 'management', 'technology', 'age', 'race', 'identity', 'color', 'religion', 
    'origin', 'sexual', 'veteran', 'learn', 'coding', 'languages', 'following', 'high', 
    'employment', 'just', 'difference', 'engineer', 'join', 'make', 'written', 'benefits',
    'users', 'sex', 'implementation', 'large', 'applicants', 'stay', 'diverse',
    'people', 'marital', 'develop', 'internal', 'broad', 'city', 'partners', 'applying', 'closely',
    'customer', 'cloud', 'qualified', 'degree', 'innovative', 'career','algorithms',
    'responsible', 'drive', 'big', 'grow', 'excellent', 'highly', 'industry',
    'search', 'improve', 'proud', 'citizenship', 'developer', 'project', 'passion',
    'ability', 'responsibilities', 'care', 'test', 'variety', 'want', 'www', 'basic',
    'sciences', 'community', 'consider', 'know', 'forward', 'organization', 'total',
    'culture', 'processing', 'architecture', 'view', 'knowledge', 'great', 'enterprise', 'agencies', 
    'understanding', 'fast', 'complex', 'strong', 'grand', 'rounds', 'teams', 'challenging', 
    'testing', 'year', 'thrive', 'affirmative', 'action', 'standards', 'features', 
    'impact', 'performance', 'use', 'collaborate', 'millions', 'paced', 'future', 
    'using', 'field', 'designing', 'solving', 'environment', 'deliver', 'devices',
    'generation', 'projects', 'equivalent', 'quality', 'end', 'solve', 'existing', 
    'meet', 'celebrate', 'benefit', 'workplace', 'committed', 'oral', 'employee',
    'consistent', 'policy', 'special', 'requires', 'accommodation', 'let', 'house',
    'emailing', 'candidateaccommodations', 'recruitment', 'does', 'agency', 'jobs', 'alias', 
    'fees', 'unsolicited', 'love', 'day', 'computing', 'rapidly', 'resources',
    'chance', 'explore', 'edge', 'position', 'provides', 'class', 'concepts', 'currently',
    'offices', 'leading', 'social', 'display', 'create', 'basis', 'creative', 
    'critical', 'apps', 'problem', 'issues', 'growing', 'communication', 'expertise',
    'infrastructure', 'resolutions', 'desired', 'services', 'given', 'locations',
    'source', 'open', 'authorization', 'united', 'states', 'careers', 'user', 'change', 
    'opportunities', 'challenges', 'massive', 'leadership', 'possible', 'available',
    'cutting', 'located', 'office', 'growth', 'demonstrate', 'demonstrated', 'events',
    'better', 'globe', 'talented', 'provide', 'modern', 'techniques', 'like',
    'various', 'visual', 'used', 'developers', 'diversity', 'engagement', 'making',
    'implementing', 'succeed', 'billions', 'continue', 'help', 'understand',
    'helping', 'current', 'defect', 'approved', 'cases', 'control', 'analysis', '000',
    'seeking', 'developing', 'apply', 'think', 'areas', 'needs', 'analyze', 'member',
    'right', 'access', 'collaboration', 'consulting', 'description', 'different',
    'effective', 'experiences','evaluate', 'largest', 'leaders', 'libraries', 'focused',
    'set', 'solution', 'core', 'goals', 'familiarity', 'process', 'able', 'focus',
    'delivery', 'general', 'getting', 'learning', 'machine', 'production', 'success',
    'hiring', 'ideal', 'self', 'structures', '2018', 'good', 'hands',
    'oriented', 'successful', 'implement', 'individual', 'individuals', 'limited',
    'motivated', 'bring',  'asset', 'businesses', 'directly', 'planning', 'assets', 'brand',
    'potential', 'present', 'private', 'programs','activity','range',
    'lead', 'record', 'driven', 'key', 'media', 'minimum', 'ny',
    'manage', 'members', 'professional', 'program', 'results',
    'insights', 'real', 'candidate', 'client', 'clients', 'global',
    'scale', 'intelligence', 'track', 'type', '00',
    'resume', 'salary', 'self'
])
